dagl_config:
  chop: true
  cpu: false
  n_GPUs: 1
  n_feats: 16
  n_resblocks: 2
  pre_train: ''
  print_model: false
  res_scale: 1.0
  resume: 0
  rgb_range: 255
  save_models: false
  scale: 2
  seed: 42
  self_ensemble: false
feature_dim:
- 6
- 8
- 10
len_prompt:
- 5
- 5
- 5
low_mem: false
lr: 0.0002
lr_gamma: 0.1
lr_step_size: 11
n_bottleneck_cab: 1
n_dec_cab:
- 1
- 1
- 1
n_enc_cab:
- 1
- 1
- 1
n_feat0: 4
n_skip_cab:
- 1
- 1
- 1
no_use_ca: false
num_adj_slices: 1
num_cascades: 2
prompt_dim:
- 2
- 4
- 6
prompt_size:
- 16
- 8
- 4
sens_feature_dim:
- 3
- 4
- 5
sens_n_feat0: 2
sens_prompt_dim:
- 1
- 2
- 3
use_checkpoint: null
weight_decay: 0.01
